version: "3.8"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - "C:/Projects/INF 692:/src/Projects"

    container_name: meu_jupyter
    ports:
      - "8888:8888"
    