version: "3.8"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu_jupyter
    volumes:
      - /mnt/c/Projects/INF\ 692:/workspace
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
