version: "3.8"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: atividadecurta6-jupyter
    container_name: atividadecurta6-jupyter
    volumes:
      - '/mnt/c/Projects/INF 692:/todo'
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    

